### PR TITLE
Replace Werkzeug.contrib.cache with cachelib

### PR DESCRIPTION
**Pull request by rillian**
Attempt to bump some dependencies to un-bitrot this.
- `urltools` 0.3.2 went away
- `werkzeug.contrib.cache` is now `cachelib`

NB I haven't gotten the tests to run, so please take that into account when reviewing!

### CODE REVIEW

**Comment by rillian** [comment]
Didn't pass travis tests, but it got further than the main branch does!

Possible next problem:

    ModuleNotFoundError: No module named 'rdflib.py3compat'

**Comment by PonteIneptique** [comment]
Thanks @rillian . Nautilus has really been put to sleep right now, because we were waiting a lot for https://github.com/TEIC/TEI/pull/1983 which has been finally merged this week :) Although, it does make sense to have a working iteration of Nautilus for the moment. I'll try to have a look to give pointers ;)

The next iteration of Nautilus is probably gonna be "simpler": it will provide blueprint generators using "any" resolver you feed it. It will probably propose other resolvers, more efficient but everything won't be as integrated as it is now. It will probably be much simpler to maintain ;)

**Comment by PonteIneptique** [comment]
Oh, it seems the only thing not working is RDFLib Sqlalchemy. I think we can decide to drop support is no one is using it (given the fact it was much slower than everything else...)

**Comment by PonteIneptique** [comment]
(Can you merge the updated dev ? I moved the test matrix to higher python versions)

**Comment by rillian** [comment]
> The next iteration of Nautilus is probably gonna be "simpler": it will provide blueprint generators using "any" resolver you feed it. It will probably propose other resolvers, more efficient but everything won't be as integrated as it is now. It will probably be much simpler to maintain ;)

All of this sounds positive. In the meantime, as you say, it would be nice to have a release that works with current pypi packages.

I don't use the RDFlib support at all.

> I moved the test matrix to higher python versions)

Looks like you need to bump the coveralls submission version as well?

**Comment by PonteIneptique** [comment]
@rillian, see https://github.com/Capitains/Nautilus/pull/91 based on your previous work ;)

**Pull request closed without merging**
