### PR TITLE
Dts draft 1

### PR DESCRIPTION
**Pull request by PonteIneptique**

### CODE REVIEW

**Comment by sonofmun** [comment]
Anything I can do to help here? I just discovered that I won't be able to upgrade us to DTS until Nautilus has been upgraded.

**Comment by PonteIneptique** [comment]
I am lost regarding where I left that. I think this is okayish, could you make a commit with a Pip install using the release version of MyCapytain ?

**Comment by sonofmun** [comment]
Will do.

**Comment by sonofmun** [comment]
"Can't find a local Berkeley DB installation."
What do I need to do to correct this?

**Comment by PonteIneptique** [comment]
Most of it can be found in https://github.com/Capitains/Nautilus/blob/dev/.travis.yml : `sudo apt-get install -y libdb5.3 libdb-dev`

**Comment by PonteIneptique** [comment]
We need to retire the - 3.4 version as well given the lxml restriction

**Comment by sonofmun** [comment]
I will see what I can figure out about this in the next couple of days. Should I push directly to this branch? Or should I do PRs to this branch that you can look at?

**Comment by PonteIneptique** [comment]
Maybe fork the branch yes, that would allow me to review the changes :)

**Comment by sonofmun** [comment]
All failed tests are in the test_cli. There are errors in TestManager because the click.commands are not recognized. And then in TestManagerClickMethod the tests fail, apparently because the caches are not actually cleared.
I don't really know enough about either of these to delve into them deeply. So I guess I will leave them with you.

**Comment by PonteIneptique** [comment]
Given the fact we only merge to dev, I take the executive decision to merge despite the error in the CLI. This means you can actually work with a stable program API.

**Comment by sonofmun** [comment]
It probably would be better if you merge so that you can describe all the changes that were made. Plus setup.py needs to updated, etc.

**Pull request merged**
